# Site settings
title: Spencer Poisseroux
description: >
    Spencer Poisseroux
author: Spencer Poisseroux
email: spoisseroux@me.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://spoisseroux.github.io" # the base hostname & protocol for your site
twitter_username: spoisseroux
github_username:  spoisseroux

#disqus_shortname: YourDisqusShortname

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title
sass:
    style: compressed

gems:
  - jemoji
  - jekyll-sitemap
# - amp-jekyll # Acceletrated Mobile Pages

remote_theme: pmarsceill/just-the-docs

# AMP Settings
# ampdir: amp/
# enable_amp: true

# Google Analytics
# google_analytics: UA-XXXXXXXX-X
